#!/bin/bash
#PBS -l walltime=00:20:00
#PBS -l nodes=1:ppn=12
#PBS -N matmul
#PBS -q cs
#PBS -W group_list=19fa-cs420d3-vtune

cd $PBS_O_WORKDIR
module load intel/.19.0
allSize=(2 4 5 8 10 16 20 25 40 50 80 100 125 200 250 400 500 1000)
for b in ${allSize[@]}; do
  echo "running with n=2000, b=$b"
  ./randMatrix 2000 2000 2000 2000 > test.txt
  amplxe-cl -collect memory-access ./matrix-nop -oa -t $b < test.txt
done